<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIRHPA7t\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIRHPA7t/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIRHPA7t.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIRHPA7t\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIRHPA7t\App_KernelDevDebugContainer([
    'container.build_hash' => 'IRHPA7t',
    'container.build_id' => 'e852b998',
    'container.build_time' => 1654089896,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIRHPA7t');
