<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNgoAe47\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNgoAe47/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNgoAe47.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNgoAe47\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNgoAe47\App_KernelDevDebugContainer([
    'container.build_hash' => 'NgoAe47',
    'container.build_id' => 'cb5c1b36',
    'container.build_time' => 1653994481,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNgoAe47');
